spring:
  application:
    name: SWAGGER-HUB
  jpa:
    generate-ddl: true
    
server:
  port: '9001'
  
management:
  endpoints:
    web:
      exposure:
        include: refresh
senior:
  citizen: Jadoo
junior:
  citizen: Jaddi