spring:
  application:
    name: libraryapp
    
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/customerportallibrary
    password: root
  jpa:
    generate-ddl: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  
  
management:
  endpoints:
    web:
      exposure:
        include: refresh

